# tasks file for komodo-ide
---
- name: create (download) directory
  file:
    path: "{{ komodo_ide_downloads_path }}"
    state: directory
    owner: root
    group: root
    mode: 0755
  tags:
    - configuration
    - komodo-ide
    - komodo-ide-download

- name: download
  get_url:
    url: "{{ komodo_ide_downloads_url }}"
    dest: "{{ komodo_ide_downloads_path }}/Komodo-IDE-{{ komodo_ide_version }}-{{ komodo_ide_build }}-linux-{{ komodo_ide_machine_map[ansible_machine] }}.tar.gz"
    owner: root
    group: root
    mode: 0644
  tags:
    - configuration
    - komodo-ide
    - komodo-ide-download

- name: extract
  command: >
    tar -xzvf "{{ komodo_ide_downloads_path }}/Komodo-IDE-{{ komodo_ide_version }}-{{ komodo_ide_build }}-linux-{{ komodo_ide_machine_map[ansible_machine] }}.tar.gz"
  args:
    chdir: "{{ komodo_ide_downloads_path }}"
    creates: "{{ komodo_ide_downloads_path }}/Komodo-IDE-{{ komodo_ide_version }}-{{ komodo_ide_build }}-linux-{{ komodo_ide_machine_map[ansible_machine] }}/install.sh"
  register: _unarchive
  tags:
    - configuration
    - komodo-ide
    - komodo-ide-extract

- name: install
  command: ./install.sh --install-dir {{ komodo_ide_install_prefix }}/Komodo-IDE-{{ komodo_ide_version }}-{{ komodo_ide_build }}
  args:
    chdir: "{{ komodo_ide_downloads_path }}/Komodo-IDE-{{ komodo_ide_version }}-{{ komodo_ide_build }}-linux-{{ komodo_ide_machine_map[ansible_machine] }}"
  when: _unarchive | changed
  tags:
    - configuration
    - komodo-ide
    - komodo-ide-install
    - komodo-ide-install-dir

- name: install (symlink)
  file:
    src: "{{ komodo_ide_install_prefix }}/Komodo-IDE-{{ komodo_ide_version }}-{{ komodo_ide_build }}/bin/komodo"
    dest: /usr/local/bin/komodo
    state: link
    force: true
  tags:
    - configuration
    - komodo-ide
    - komodo-ide-install
    - komodo-ide-install-symlink
