# tasks file for komodo-ide
---
- name: create (download) directory
  debug:
    msg: "{{ komodo_ide_series }}"
  failed_when: true
  tags:
    - configuration
    - komodo-ide
    - komodo-ide-download

- name: create (download) directory
  file:
    path: "{{ komodo_ide_downloads_path }}"
    state: directory
    owner: root
    group: root
    mode: 0755
  tags:
    - configuration
    - komodo-ide
    - komodo-ide-download

- name: download
  get_url:
    url: "http://downloads.activestate.com/Komodo/releases/{{ komodo_ide_version }}/Komodo-IDE-{{ komodo_ide_version }}-{{ komodo_ide_build }}-linux-{{ komodo_ide_machine_map[ansible_machine] }}.tar.gz"
    dest: "{{ komodo_ide_downloads_path }}/Komodo-IDE-{{ komodo_ide_version }}-{{ komodo_ide_build }}-linux-{{ komodo_ide_machine_map[ansible_machine] }}.tar.gz"
    owner: root
    group: root
    mode: 0644
  tags:
    - configuration
    - komodo-ide
    - komodo-ide-download

- name: extract
  unarchive:
    src: "{{ komodo_ide_downloads_path }}/Komodo-IDE-{{ komodo_ide_version }}-{{ komodo_ide_build }}-linux-{{ komodo_ide_machine_map[ansible_machine] }}.tar.gz"
    dest: "{{ komodo_ide_downloads_path }}/"
    owner: root
    group: root
    mode: 0755
    creates: "{{ komodo_ide_downloads_path }}/Komodo-IDE-{{ komodo_ide_version }}-{{ komodo_ide_build }}-linux-{{ komodo_ide_machine_map[ansible_machine] }}/install.sh"
    copy: false
  register: unarchive
  tags:
    - configuration
    - komodo-ide
    - komodo-ide-extract

- name: chown
  file:
    path: "{{ komodo_ide_downloads_path }}/Komodo-IDE-{{ komodo_ide_version }}-{{ komodo_ide_build }}-linux-{{ komodo_ide_machine_map[ansible_machine] }}"
    state: directory
    owner: root
    group: root
    recurse: true
  when: unarchive | changed and (ansible_version is not defined or ansible_version.full | version_compare('1.9', '<'))
  tags:
    - configuration
    - komodo-ide
    - komodo-ide-chown

- name: install
  command: ./install.sh --install-dir {{ komodo_ide_install_prefix }}/Komodo-IDE-{{ komodo_ide_version }}-{{ komodo_ide_build }}
  args:
    chdir: "{{ komodo_ide_downloads_path }}/Komodo-IDE-{{ komodo_ide_version }}-{{ komodo_ide_build }}-linux-{{ komodo_ide_machine_map[ansible_machine] }}"
  when: unarchive | changed
  tags:
    - configuration
    - komodo-ide
    - komodo-ide-install
    - komodo-ide-install-dir

- name: install (symlink)
  file:
    src: "{{ komodo_ide_install_prefix }}/Komodo-IDE-{{ komodo_ide_version }}-{{ komodo_ide_build }}/bin/komodo"
    dest: /usr/local/bin/komodo
    state: link
    force: true
  tags:
    - configuration
    - komodo-ide
    - komodo-ide-install
    - komodo-ide-install-symlink
